import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
 import styles  from './styles.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SettingsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header className={styles.header}>
        <Link href="/password"> Password </Link>
        <Link href="/logout"> Logout </Link>
      </header>
      <section>{children}</section>
    </>
  )
}
